export const properties = [
  /*   {
    id: 1,
    houseNo: "A1",
    type: "Snohetta",
    sakadastroKodi: "01.72.16.104.067",
    landSize: "3214",
    buildingSpace: "",
    coords:
      "1259.25,821.63,1319.91,744.48,1434.17,818.10,1432.41,826.93,1428.87,834.59,1316.97,869.34,1259.25,821.63",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  }, */
  /*  {
    id: 2,
    houseNo: "A2",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.027",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 3,
    houseNo: "A3",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.026",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 4,
    houseNo: "A4",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.025",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 5,
    houseNo: "A5",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.024",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 6,
    houseNo: "A6",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.023",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 7,
    houseNo: "A7",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.022",
    landSize: "1900",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  }, */
  {
    id: 8,
    houseNo: "A8",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.052",
    landSize: "1414",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/a8.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 9,
    houseNo: "A9",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.063",
    landSize: "1414",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/a9.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 10,
    houseNo: "A10",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.057",
    landSize: "1414",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/a10.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 11,
    houseNo: "A11",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.070",
    landSize: "1414",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/a11.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 12,
    houseNo: "A12",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.066",
    landSize: "1414",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/a12.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 13,
    houseNo: "A13",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1932",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 14,
    houseNo: "A14",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1056",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 15,
    houseNo: "A15",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1087",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 16,
    houseNo: "A16",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1114",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 17,
    houseNo: "A17",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1098",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 18,
    houseNo: "A18",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 19,
    houseNo: "A19",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 20,
    houseNo: "A20",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 21,
    houseNo: "A21",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 22,
    houseNo: "A22",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 23,
    houseNo: "A23",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 24,
    houseNo: "A24",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 25,
    houseNo: "A25",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 26,
    houseNo: "A26",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 27,
    houseNo: "A27",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 28,
    houseNo: "A28",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1090",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 29,
    houseNo: "A29",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1910",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 30,
    houseNo: "B1",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.082",
    landSize: "1008",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b1.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 31,
    houseNo: "B2",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.077",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b2.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 32,
    houseNo: "B3",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.050",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b3.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 33,
    houseNo: "B4",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.058",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b4.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 34,
    houseNo: "B5",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.068",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b5.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 35,
    houseNo: "B6",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.059",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b6.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 36,
    houseNo: "B7",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.045",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b7.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 37,
    houseNo: "B8",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.040",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b8.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 38,
    houseNo: "B9",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.065",
    landSize: "1093",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/b9.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 39,
    houseNo: "B10",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1263",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 40,
    houseNo: "B11",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 41,
    houseNo: "B12",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 42,
    houseNo: "B13",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 43,
    houseNo: "B14",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 44,
    houseNo: "B15",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 45,
    houseNo: "B16",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 46,
    houseNo: "B17",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 47,
    houseNo: "B18",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 48,
    houseNo: "B19",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 49,
    houseNo: "B20",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 50,
    houseNo: "B21",
    type: "Private House",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1000",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 51,
    houseNo: "C1",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.041",
    landSize: "1102",
    buildingSpace: "",
    coords:
      "1239.81,894.08,1211.54,932.36,1259.25,968.88,1276.33,919.99,1239.81,894.08",
    twoDImg: "/2d/c1.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 52,
    houseNo: "C2",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.080",
    landSize: "1009",
    buildingSpace: "",
    coords:
      "1208.01,873.46,1179.15,911.16,1212.13,933.54,1239.81,893.49,1208.01,873.46",
    twoDImg: "/2d/c2.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 53,
    houseNo: "C3",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.071",
    landSize: "1009",
    buildingSpace: "",
    coords:
      "1149.11,888.78,1178.56,849.31,1208.59,872.87,1178.56,910.57,1149.11,888.78",
    twoDImg: "/2d/c3.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 54,
    houseNo: "C4",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.043",
    landSize: "1008",
    buildingSpace: "",
    coords:
      "1117.30,865.22,1149.05,826.91,1178.83,850.03,1149.26,889.18,1117.30,865.22",
    twoDImg: "/2d/c4.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 55,
    houseNo: "c5",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.072",
    landSize: "1009",
    buildingSpace: "",
    coords:
      "1091.39,845.78,1120.84,803.37,1150.28,825.75,1117.89,865.22,1091.39,845.78",
    twoDImg: "/2d/c5.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 56,
    houseNo: "C6",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.0051",
    landSize: "1009",
    buildingSpace: "",
    coords:
      "1090.33,845.23,1055.97,822.95,1089.70,778.81,1120.52,803.59,1090.33,845.23",
    twoDImg: "/2d/c6.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 57,
    houseNo: "C7",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.064",
    landSize: "1007",
    buildingSpace: "",
    coords:
      "1027.48,802.49,1058.40,760.67,1089.32,779.52,1056.63,822.22,1027.48,802.49",
    twoDImg: "/2d/c7.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 58,
    houseNo: "C8",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.0075",
    landSize: "1000",
    buildingSpace: "",
    coords:
      "998.33,781.88,1029.54,740.65,1058.40,761.56,1028.36,802.49,998.33,781.88",
    twoDImg: "/2d/c8.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 59,
    houseNo: "C9",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.062",
    landSize: "1006",
    buildingSpace: "",
    coords:
      "970.64,763.91,1005.10,711.20,1027.19,727.40,1024.54,730.94,1029.25,739.77,997.44,782.18,970.64,763.91",
    twoDImg: "/2d/c9.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 60,
    houseNo: "C10",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.069",
    landSize: "1030",
    buildingSpace: "",
    coords:
      "940.90,746.54,975.65,698.83,985.08,695.88,1005.40,710.31,969.47,764.50,940.90,746.54",
    twoDImg: "/2d/c10.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 61,
    houseNo: "C11",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.046",
    landSize: "1029",
    buildingSpace: "",
    coords:
      "903.80,725.33,936.78,675.86,973.88,698.83,940.01,746.24,903.80,725.33",
    twoDImg: "/2d/c11.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 62,
    houseNo: "C12",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.076",
    landSize: "1353",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c12.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 63,
    houseNo: "C13",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.053",
    landSize: "1276",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c13.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 64,
    houseNo: "C14",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.042",
    landSize: "1295",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c14.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 65,
    houseNo: "C15",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1235",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c15.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 66,
    houseNo: "C16",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1238",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c16.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 67,
    houseNo: "C17",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1281",
    buildingSpace: "",
    coords: "",
    twoDImg: "/2d/c17.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 68,
    houseNo: "C18",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1241",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 69,
    houseNo: "C19",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1207",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 70,
    houseNo: "C20",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1180",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 71,
    houseNo: "C21",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1171",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 72,
    houseNo: "C22",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1173",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 73,
    houseNo: "C23",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1181",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 74,
    houseNo: "C24",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1183",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 75,
    houseNo: "C25",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1194",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 76,
    houseNo: "C26",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1204",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 77,
    houseNo: "C27",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1209",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 78,
    houseNo: "C28",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1211",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 79,
    houseNo: "C29",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1221",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 80,
    houseNo: "C30",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1221",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 81,
    houseNo: "C31",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1227",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 82,
    houseNo: "C32",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1226",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 83,
    houseNo: "C33",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.012",
    landSize: "1059",
    buildingSpace: "",
    coords: "",
    twoDImg: null,
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 84,
    houseNo: "D1",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.055",
    landSize: "1461",
    buildingSpace: "",
    coords:
      "1209.77,934.13,1256.30,968.88,1231.93,1003.54,1221.94,1002.29,1176.54,972.30,1209.77,934.13",
    twoDImg: "/2d/d1.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 85,
    houseNo: "D2",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.049",
    landSize: "1001",
    buildingSpace: "",
    coords:
      "1144.89,950.81,1177.79,911.25,1209.77,932.66,1176.20,971.83,1144.89,950.81",
    twoDImg: "/2d/d2.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 86,
    houseNo: "D3",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.044",
    landSize: "1001",
    buildingSpace: "",
    coords:
      "1114.07,930.82,1149.47,889.17,1178.62,911.25,1144.05,951.64,1114.07,930.82",
    twoDImg: "/2d/d3.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 87,
    houseNo: "D4",
    type: "Private Villa",
    sakadastroKodi: "01.72.16.104.048",
    landSize: "1000",
    buildingSpace: "",
    coords:
      "1084.50,910.00,1117.40,865.43,1149.47,890.01,1113.65,930.82,1084.50,910.00",
    twoDImg: "/2d/d4.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 88,
    houseNo: "D5",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.047",
    landSize: "1001",
    buildingSpace: "",
    coords:
      "1055.75,891.13,1089.91,844.90,1117.59,864.63,1083.43,910.87,1055.75,891.13",
    twoDImg: "/2d/d5.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 89,
    houseNo: "D6",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.078",
    landSize: "1001",
    buildingSpace: "",
    coords:
      "1024.11,869.60,1056.60,821.70,1090.33,845.44,1056.18,891.67,1024.11,869.60",
    twoDImg: "/2d/d6.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 90,
    houseNo: "D7",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.060",
    landSize: "1002",
    buildingSpace: "",
    coords:
      "993.29,850.02,1027.86,801.30,1057.01,822.12,1022.86,870.43,993.29,850.02",
    twoDImg: "/2d/d7.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: true,
  },
  {
    id: 91,
    houseNo: "D8",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.061",
    landSize: "1001",
    buildingSpace: "",
    coords:
      "962.89,830.03,997.87,780.89,1028.27,801.71,992.87,850.44,962.89,830.03",
    twoDImg: "/2d/d8.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 92,
    houseNo: "D9",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.081",
    landSize: "1005",
    buildingSpace: "",
    coords:
      "935.82,812.96,969.97,763.40,998.29,782.14,961.64,830.87,935.82,812.96",
    twoDImg: "/2d/d9.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 93,
    houseNo: "D10",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.054",
    landSize: "1002",
    buildingSpace: "",
    coords:
      "905.00,795.47,939.72,746.24,969.76,764.50,935.60,813.68,905.00,795.47",
    twoDImg: "/2d/d10.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
  {
    id: 94,
    houseNo: "D11",
    type: "Land Plot ",
    sakadastroKodi: "01.72.16.104.073",
    landSize: "1068",
    buildingSpace: "",
    coords:
      "903.50,724.74,940.31,746.53,904.68,795.42,869.05,781.88,867.87,776.00,903.50,724.74",
    twoDImg: "/2d/d11.webp",
    view: "",
    sector: "",
    totalHouseArea: "",
    firstFloor: "",
    secondFloor: "",
    terraceArea: "",
    terraceFirstFloor: "",
    terraceSecondFloor: "",
    ceilingHeights: "",
    entranceHall: "",
    mainAreas: "",
    bedrooms: "",
    isSold: false,
  },
];
